.TH cfv 1 "05 Oct 2000"
.SH NAME
cfv \- Verify file concistency with .sfv, .csv, or md5sum files
.SH SYNOPSIS
.B cfv [-v|-V] [-r|-rr|-R] [-T|-C] [-m|-M] [-t type] [-f file] [files...]
.SH DESCRIPTION
.B cfv
verifies that the files you have are the same as those that the were used to create
the checksum file.
.SH OPTIONS
.PP
.IP "-v"
Enable printing of extra messages.
.IP "-V"
Disable printing of extra messages. (default)
.IP "-r"
Recursive mode 1.  In create mode, make seperate chksum files for each dir.
.IP "-rr"
Recursive mode 2.  In create mode make a single file with deep listing in it.
Both recursive modes are equivilant for test mode.
.IP "-R"
Disable recursive mode (default)
.IP "-T"
Set test mode. (default)
.IP "-C"
Set create mode.
.IP "-m"
check only for missing files (don't compare checksums)
.IP "-M"
check checksums (default)
.IP "-f file"
Specify the name of the checksum file to test or create.
.IP "-t type"
Specify the type of the file.  Can be sfv, csv, csv2, md5, or auto.  The default is auto,
which will detect the file type for you.  When creating, if type is auto an sfv
will be made, unless a different default has been set in the config file.
.P
.B sfv
is a simply file verify format file
.br
.B csv
is a comma seperated value file, with the fields being name,size,crc32,
.br
.B csv2
is a comma seperated value file, with the fields being name,size,
.br
.B md5
is md5sum format file
.SH EXAMPLES
If no options are specified, the default will be -T -t auto, and it will search the current directory for any sfv or csv files.
.br
.B
cfv
.P
Force the file to test:
.br
.B
cfv -f funny.name
.P
Test only the files you have, (avoid file not found errors):
.br
.B
cfv *
.P
Create a csv file for all the files in the current dir:
.br
.B
cfv -C -tcsv
.P
Create a csv file for only the zip files in the current dir, and specify the filename:
.br
.B
cfv -C -tcsv -fsomezips.csv *.zip
.SH CONFIGURATION
Upon startup, cfv will test for ~/.cfvrc and if it exists, read configuration information from it.
The file consists of any number of lines, each having a single option name and the value seperated by a space.
Empty lines and lines beginning with a # are ignored.
.SH EXAMPLE CONFIGURATION
#this is an example .cfvrc that specifies all the default options
.br
#don't be verbose
.br
verbose 0
.br
#create sfv files by default
.br
default sfv
.br
#sort dir listings before creating a checksum file
.br
dirsort 1
.br
#sort command line specified files
.br
cmdlinesort 1
.br
#don't be recursive (set to 0 for -R,  1 for -r,  2 for -rr)
.br
recursive 0
.SH FILES
.PP
.IP "~/.cfvrc"
cfv configuration file.  See configuration section.
.SH AUTHOR
Matt Mueller <donut@azstarnet.com>
.P
The latest version, and other programs I have written, are available from:
.br
http://www.azstarnet.com/~donut/programs/cfv.html
.SH "SEE ALSO"
.BR md5sum(1)
